url: "jacksydney.ca" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Jack Sydney Schwartz" # the name of your site, e.g. ACME Corp.
description: "Astrodynamics PhD Student at Princeton University"
